const CampSite = [
    {
        id: 1,
        name: "힐링피아 카라반 글램핑 풀 캠핑장",
        lineIntro: "별보기 좋은 카라반 캠핑장",
        intro: "힐링피아 카라반 글램핑 풀 캠핑장은 어비계곡 사기막천과 유명산 벽계천이 합류하는 두물머리에 위치하고 있다. 카라반 데크의 크기는 휴식공간용과 바베큐공간을 분리 할 정도의 넓은 공간이고 각 카라반에 개별 수영장이 있다. 놀이시설로는 개별수영장 별도의 야외수영장, 어린이 암벽 ,하늘자전거,탁구대 등이 있으며, 힐링하기 좋은 전망대가 있어 밤에 별보기 좋은 카라반 캠핑장이다.",
        allar: 6600,
        featureNm:
            "어비계곡 하류 합수점에 위치한 풀빌라형 카라반  힐링피아 카라반 글램핑 풀 캠핑장은 어비계곡 사기막천과 유명산 벽계천이 합류하는 두물머리에 위치하고 있다. 카라반 데크의 크기는 휴식공간용과 바베큐공간을 분리 할 정도의 넓은 공간이고 각 카라반에 개별 수영장이 있다. 놀이시설로는 개별수영장 별도의 야외수영장, 어린이 암벽 ,하늘자전거,탁구대 등이 있으며, 힐링하기 좋은 전망대가 있어 밤에 별보기 좋은 카라반 캠핑장이다. ",
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 설악면 유명산길 61-75",
        addr2: "설악면 유명산길 61-75",
        mapX: 127.4947241,
        mapY: 37.5978864,
        tel: "010-3148-9970",
        homepage: "http://healingpia.co.kr",
        price: 220000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: [
            "계곡 물놀이",
            "산책로",
            "강/물놀이",
            "수영장",
            "청소년체험시설",
        ],
        themaEnvrnCl: [
            "액티비티",
            "봄꽃여행",
            "여름물놀이",
            "가을단풍명소",
            "겨울눈꽃명소",
            "걷기길",
        ],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "온수", "마트.편의점"],
        eqpmnLendCl: ["릴선", "화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100002/thumb/thumb_720_20339geHYKzGA9OjsoC0nFwX.jpg",
    },
    {
        id: 2,
        name: "웨이브파크 카라반",
        lineIntro: "인공 서핑장 웨이브 파크에서 운영하는 카라반 숙소",
        intro: "일상의 무게를 잠시 내려놓고 힐링할 수 있는 공간이 필요하다면 지금 바로 방문해주세요. 저희 카라반은 국내 최고 업체인 STAUS사에서 최고급 시설로 제작하였고 개별 샤워실 및 화장실, TV, 냉장고, 인덕션, 전자레인지 등의 각종 편의 시설이 구비되어 있습니다. 카라반 테라스에서는 프라이빗한 바베큐를 사시사철 즐길 수 있으며 혼자 와도 좋고 가족, 연인, 친구와 함께 오면 더욱 좋은 공간입니다. 바로 옆에 웨이브 파크가 위치하고 있어 즐길거리와 먹거리도 다양합니다. 거북섬의 정취와 호수가 어우러져 마치 휴양지에 온듯한 착각을 주며 평화로운 분위기의 산책로에서 맛보는 일몰도 기가 막힙니다. 아름다운 서해의 석양을 바라보며 잊지못할 추억을 만드세요.",
        allar: 0,
        featureNm: "해안가 산책로, 15분 거리에 시흥프리미엄 아울렛. ",
        isGlamp: false,
        isCaravan: true,
        isAuto: false,
        sigunguNm: "시흥시",
        addr1: "경기 시흥시 거북섬둘레길 42 (정왕동)",
        addr2: "거북섬둘레길 42 (정왕동)",
        mapX: 126.6806875,
        mapY: 37.3241008,
        tel: "031-420-9750",
        homepage: "https://wavepark.co.kr/wave/caravanInfo",
        price: 170000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["산책로"],
        themaEnvrnCl: ["일몰명소", "수상레저", "여름물놀이", "걷기길"],
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "물놀이장",
            "마트.편의점",
        ],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100011/thumb/thumb_720_5075dWVFnpgjhhh7pyVKfOaP.jpg",
    },
    {
        id: 3,
        name: "약수동산",
        lineIntro: "남한강을 따라 양평시내까지 내려다 보이는 전망좋은  캠핑장",
        intro: "약수동산은 남한강을 따라 양평시내까지 내려다 보이는 전망좋은  캠핑장이다. 남한강이 바로 옆에 있고 봄이면 벚꽃이 만개하는 등, 뷰가 좋은 캠핑장으로 유명하다. 경의중앙선 아신역에서 도보로 15분 거리에 있어 접근성이 뛰어나다. 우백호 존 4개과 배산임수 존 4개이 남한강을 가까이에서 볼 수 있어 인기가 많은데, 특히 배산임수 스페셜 사이트는 명당자리로 예약이 어렵다. 좌청룡 존 7개는 지대가 높아 시야가 트여 있으며, 노을 존 4개는 낮은 지대에 있고, 애견 동반이 가능하다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "양평군",
        addr1: "경기 양평군 옥천면 약수동산길 86",
        addr2: "옥천면 약수동산길 86",
        mapX: 127.455147,
        mapY: 37.50762979,
        tel: "031-771-4664",
        homepage: "https://www.instagram.com/yaksudongsan",
        price: 100000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: ["봄꽃여행", "가을단풍명소"],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "운동시설"],
        eqpmnLendCl: ["릴선", "화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100013/thumb/thumb_720_0116MYDYyd0g3mtKa0wliblU.jpeg",
    },
    {
        id: 4,
        name: "밤벌캠핑장",
        lineIntro: "한옥 관리실이 인상적인 강변 야영장",
        intro: "팔봉산 유원지에서 차로 7분 거리에 있는 오토캠핑장이다. 파쇄석으로 된 캠핑장 사이트는 예약 후, 캠핑 당일 선착순으로 현장에서 배정을 받는다. 늦을 경우 원하는 사이트를 받지 못할 수도 있다. 캠핑장 앞을 흐르는 어비계곡은 수심이 깊지 않아 아이들과 함께 놀기 좋다. 캠핑장을 둘러싼 커다란 나무들 덕분에 여름에도 시원한 그늘에서 캠핑을 즐길 수 있다. 관리동에는 매점과 샤워실, 화장실, 싱크대를 이용할 수 있다. 마당 한쪽에는 아이들이 가지고 놀 수 있는 장난감과 놀이방도 마련되어 있다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 설악면 어비산길 15-23",
        addr2: "설악면 어비산길 15-23",
        mapX: 127.4947099,
        mapY: 37.6012926,
        tel: "031-585-8740",
        homepage: NaN,
        price: 240000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: ["여름물놀이"],
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "운동시설",
            "마트.편의점",
        ],
        eqpmnLendCl: ["텐트", "릴선", "화로대", "난방기구", "식기"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100021/thumb/thumb_720_2470XLGMtPpqynNQw6kToeSY.jpg",
    },
    {
        id: 5,
        name: "청춘캠핑장",
        lineIntro:
            "한강 금대리 레저 타운 가는 길에 있는 작은 규모의  글램핑, 카라반 캠핑장",
        intro: "북한강 금대리 레저 타운 가는 길가에 있는 작은 규모의  글램핑, 카라반 캠핑장이다. 글램핑장 내부 인테리어는 목조로 숲의 청량함이 느껴지고, 이불커버와 매트, 베개커버는 매일 교체해 청결한 환경을 유지하고 있다. 오토캠핑장과는 달리 개별 화장실과 샤워시설, 싱크대가 설치되어 있어 공용 시설에 민감한 경우에도 편안하게 이용할 수 있다. 글램핑 장 앞에 바로 넓은 풀장이 있어 물놀이를 즐기기에도 좋다. 편의점과 카페를 함께 운영중이다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: true,
        isAuto: false,
        sigunguNm: "가평군",
        addr1: "경기 가평군 가평읍 호반로 1700",
        addr2: "가평읍 호반로 1700",
        mapX: 127.5124645,
        mapY: 37.7467558,
        tel: "031-585-3103",
        homepage: "Www.toycamp.kr",
        price: 65000,
        animalCmgCl: false,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
            "내부샤워실",
        ],
        caravInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
            "내부샤워실",
        ],
        posblFcltyCl: ["수상레저"],
        themaEnvrnCl: ["수상레저", "여름물놀이"],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "운동시설"],
        eqpmnLendCl: ["화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100022/thumb/thumb_720_0632ptnKfYnPFs0yo069zOco.jpg",
    },
    {
        id: 6,
        name: "화성시 매송 오토캠핑장",
        lineIntro: "매송인근 어천저수지 옆  화성시 직영 캠핑장",
        intro: "화성도시공사에서 운영하는 화성시 매송 오토캠핑장은 칠보산 등산로 입구와 가깝다. 바로 앞에 어천저수지가 펼쳐져 있어, 등산이나 낚시를 즐기는 경우에 최적의 캠핑장이다. 봄에는 저수지 둘레로 벚꽃이 만개하여 아름다운 뷰를 가까이에서 즐길 수 있다. 총 25개의 사이트가 있고, 사이트에 바로 주차가 가능하며, 별도의 주차장은 없다. 공공 캠핑장이라서 저렴한 가격으로 1박은 물론 당일 이용도 가능한데, 당일 피크닉 캠핑은 예약이 안된 사이트에 대해서 당일 유선으로 신청 후 이용 가능하다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "화성시",
        addr1: "경기도 화성시 매송면 어천리 164 ",
        addr2: "매송면 어천리 164",
        mapX: 126.9161565,
        mapY: 37.25773423,
        tel: "031-633-0700",
        homepage: NaN,
        price: 130000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["낚시"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷"],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100031/thumb/thumb_720_6365N0EbVPiFFF8f4XiEveKv.jpg",
    },
    {
        id: 7,
        name: "캠프고일리",
        lineIntro: "한팀만 이용하는 프라이빗 독채팬션 & 캠핑장",
        intro: "포천 아도니스 골프장 인근에 위치한 캠프고일리는 단독 펜션 겸 캠핑장으로, 캠퍼들이 원하는 바를 구현한 감성 넘치는 곳이다. 잔디위에 조성된 사이트 4개와 독채 팬션, 산장을 함께 이용할 수 있는 프라이빗 야영장이다. 때문에 소규모의 그룹 캠핑이나 펜션과 캠핑을 함께 즐기려는 경우에 적합하다. 또한 사장님이 직접 운영하는 앤티크 한 캠핑 소품이 가득한 매력적인 바가 있다. 캠핑장은 널찍한 잔디밭으로 되어 있고, 단독으로 이용할 수 있어 애견 동반도 가능하다. 봄이면 만개하는 산수유나무들과 여름과 가을이면 나무 울창한 산책로까지 갖추고 있는 운치 있는 캠핑장이다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "포천시",
        addr1: "경기 포천시 신북면 포천로2337번길 38-29",
        addr2: "신북면 포천로2337번길 38-29",
        mapX: 127.1889864,
        mapY: 37.9617314,
        tel: "031-881-6384",
        homepage: "https://www.instagram.com/camp_goilly/",
        price: 220000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: NaN,
        brazierCl: "공동취사장",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "온수",
            "트렘폴린",
            "물놀이장",
            "산책로",
        ],
        eqpmnLendCl: ["릴선", "화로대", "난방기구"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100037/thumb/thumb_720_9841XB2m2LiPM2qt4ZMh2Ex1.jpg",
    },
    {
        id: 8,
        name: "읍내리 75-1 캠핑장",
        lineIntro: "자연과 함께하는 힐링캠핑장",
        intro: "이름 그대로 가평군 가평읍 읍내리 75-1에 위치한 오토캠핑장이다. 총 17개 사이트를 운영하고 있다. 사이트마다 크기가 약간 차이가 있어 예약 전에 먼저 사이트 위치와 사이즈를 확인하는 것이 좋다. 사이트는 계단식으로 되어 있으나 단차가 크지는 않다. 캠핑장 앞에 조종천이 흐르고 있어 강 뷰를 즐길 수 있다. 읍내랑 멀지 않고, 주변에 편의점과 식당도 있어 필요할 경우 이용할 수 있어 편리하다. 여름에는 캠핑장 앞에 작은 수영장도 운영하고, 조금 걸어서 나가면 다슬기 잡기가 가능한 얕은 계곡이 있다.",
        allar: 2452,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 가평읍 물안산길 42-143",
        addr2: "가평읍 물안산길 42-143",
        mapX: 127.5140734,
        mapY: 37.8552141,
        tel: "031-883-6384",
        homepage: "https://eupnaeri751.modoo.at/",
        price: 120000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["어린이놀이시설"],
        themaEnvrnCl: ["일몰명소", "낚시"],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "물놀이장", "운동시설"],
        eqpmnLendCl: ["텐트", "릴선", "화로대", "난방기구", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100045/thumb/thumb_720_5848g0PulPAv2tNBir4ifiyh.jpg",
    },
    {
        id: 9,
        name: "운악산 글램핑",
        lineIntro: "운악산 암봉이 올려다 보이는 전망좋은 글램핑장",
        intro: "운악산 자락에 위치한 규모 큰 글램핑장이다. 뒤로 운악산 암봉이 올려다 보이는 전망좋은 곳이다. 오페라 프리미엄, 카바나 글램핑, VIP로 종류가 다양한데, 사이트 별로 개별 화장실 여부가 달라서, 예약 전에 미리 확인하는 것이 좋다. 야외 수영장과 유아 수영장이 각각 있어서, 모두가 쾌적하게 이용할 수 있고, 캠핑장 바로 옆에 있는 화현계곡에서는 한여름에도 아주 차가운 계곡물을 즐길 수 있고 가을이면 단풍이 아름답다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: false,
        isAuto: false,
        sigunguNm: "포천시",
        addr1: "경기 포천시 화현면 화동로432번길 92-131",
        addr2: "화현면 화동로432번길 92-131",
        mapX: 127.3111947,
        mapY: 37.9013458,
        tel: "031-855-5081",
        homepage: "http://운악산글램핑.com/",
        price: 140000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
        ],
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: ["가을단풍명소"],
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "트렘폴린",
            "물놀이장",
            "운동시설",
        ],
        eqpmnLendCl: ["화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100056/thumb/thumb_720_7160btk9esmjqkri7hYIUQV7.jpg",
    },
    {
        id: 10,
        name: "수원 솔내음 캠핑장",
        lineIntro: "칠보산 입구에 위치한  글램핑과 카라반 전용 도심 야영장",
        intro: "수원 칠보산에 위치한 캠핑장으로, 소나무 숲과 맑은 실개천인 소하천을 끼고 있는 자연 친화적 캠핑장이다. 대중교통으로 방문이 가능하여 뚜벅이 캠퍼들도 편리하게 찾을 수 있고, 칠보산의 등산 코스도 이용 가능하다. 글램핑 15개, 카라반 15대가 있는 리조트형 캠핑장이다. 간격이 다소 좁은 것이 아쉽지만, 편의 시설이 잘 갖춰져 있어 편리하다. 위치에 따라 멀리 아파트가 보이기도 하지만, 사이사이에 나무가 많아서 자연을 느끼기엔 충분하다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: true,
        isAuto: false,
        sigunguNm: "수원시",
        addr1: "경기 수원시 권선구 칠보로 2 (금곡동)",
        addr2: "권선구 칠보로 2 (금곡동)",
        mapX: 126.9386874,
        mapY: 37.2673983,
        tel: "031-855-6102",
        homepage: NaN,
        price: 80000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        caravInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        posblFcltyCl: ["산책로"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "트렘폴린",
            "물놀이장",
            "운동시설",
            "마트.편의점",
        ],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100057/thumb/thumb_720_9310DiiOEDMUclfohTPy0IYI.jpg",
    },
    {
        id: 11,
        name: "캠핑 앨리스",
        lineIntro: "국립양평치유의숲 인근 폐교 활용 야영장",
        intro: "캠핑 앨리스은 양평 국링양평치유의 숲 인근에 있다. 폐교를 리모델링한 캠핑장으로 상큼하게 도색한 학교 건물과 푸르고 너른 잔디 운동장이 펼쳐져 있어 아이들을 동반한 가족 야영장으로 인기가 많다. 데크 사이트와 파쇄석 사이트로 나눠지는데, 총 17개의 사이트가 있고, 입실 시 선착순으로 원하는 자리를 선택할 수 있다. 부지 내에 독채 숙소도 있어서 펜션처럼 이용 가능하다. 또한 조리와 취식이 가능한 테이블들을 갖춘 조리실이 별도로 있어 편리하다. 근처에 가볼 만한 곳으로는 두물머리와 세미원 등이 있다.",
        allar: 10032,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "양평군",
        addr1: "경기도 양평군 양평면 양동로 1112",
        addr2: "양평면 양동로 1112",
        mapX: 127.7326415,
        mapY: 37.4733389,
        tel: "070-7718-1219",
        homepage: "https://camp-ya.co.kr",
        price: 80000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: [
            "계곡 물놀이",
            "산책로",
            "운동장",
            "청소년체험시설",
            "농어촌체험시설",
        ],
        themaEnvrnCl: ["봄꽃여행", "걷기길"],
        brazierCl: "개별",
        sbrsCl: ["전기", "장작판매", "온수"],
        eqpmnLendCl: ["릴선", "화로대", "난방기구"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100065/thumb/thumb_720_1439dmPZBE2AgrlktozohPPY.jpg",
    },
    {
        id: 12,
        name: "포천 글램파크 캠핑장",
        lineIntro: NaN,
        intro: NaN,
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "포천시",
        addr1: "경기 포천시 이동면 화동로 1925-47",
        addr2: "이동면 화동로 1925-47",
        mapX: 127.3691111,
        mapY: 38.02001323,
        tel: "010-2011-314",
        homepage: NaN,
        price: 145000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: NaN,
        eqpmnLendCl: ["릴선", "화로대"],
        firstImageUrl: NaN,
    },
    {
        id: 13,
        name: "메이플글램핑&카라반",
        lineIntro: "이동갈비촌에 위치한 반려견 동반 글램핑과 카라반",
        intro: "메이플 글램핑&카라반은 포천 이동갈비촌 외곽에 위치한 프라이빗 한 캠핑장이다. 글램핑 7동, 카라반 5대로  큰 규모는 아니지만, 두 개의 실외 수영장과 잔디광장, 분수연못, 트램펄린, 블루베리 농원과 단풍나무숲까지 있다. 인조잔디가 깔린 반려견 운동장 규모도 상당히 크다. 시설마다 개별 가림막이 설치되어 있어    조용하고 독립된 캠핑을 즐기기 좋다. 인근에 백운계곡, 산정호수, 평강식물원 등이 있다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: true,
        isAuto: false,
        sigunguNm: "포천시",
        addr1: "경기 포천시 이동면 화동로 2236-25",
        addr2: "이동면 화동로 2236-25",
        mapX: 127.3750054,
        mapY: 38.04441628,
        tel: "031-536-9922",
        homepage: "https://blog.naver.com/qkrtns100",
        price: 205000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
            "내부샤워실",
        ],
        caravInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
            "내부샤워실",
        ],
        posblFcltyCl: ["어린이놀이시설"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "온수"],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100069/thumb/thumb_720_1967hmCDHiRdjFFQWVcHS3L6.jpg",
    },
    {
        id: 14,
        name: "민트글램핑",
        lineIntro: NaN,
        intro: "경기도 포천 산정호수, 명성산, 백운계곡 인근에 위치한 민트글램핑은 자연 친화적인 캠핑장입니다. 명성산 자락에 위치한 캠핑장 답게 아름다운 풍광을 가지고 있으며, 숲과 산책로가 있어 신선한 공기를 마시며 산책을 즐기실 수 있습니다. 근처 산책로에는 밤나무 소나무, 참나무, 전나무 숲이 있어 숲 체험이 가능 합니다. 대지면적 약 12,000여평에 6차 산업을 접목하여 다양한 허브체험과, 허브카페를 운영하고 있으며,  봄, 여름, 가을, 겨을 계절별  농산물체험을 하실 수 있습니다. 매점에서는 장작과 숯 각종 고기와 친환경 야채를 구입 할 수 있으며, 캠핑에 필요한 다양한 용품 구입이 가능합니다. 외부의 넓은 천연 잔디 마당과 야외 수영장, 다목적 운동장에서 다양한 놀이를 즐길 수 있으며, 글램핑 전동의 개인 화장실과 샤워실을 이용하실 수 있으며 고객님의 진정한 휴식과 추억을 많이 만들 수 있도록 임직원 모두 최선을 다하겠습니다.",
        allar: 29940,
        featureNm:
            "포천 명성산 남쪽에 위치한 규모가 큰 글램핑장   포천 명성산 남쪽에 위치한 규모가 큰 민트 글램핑장은 가족단위는 물론 커플들도 만족할 글램핑장이다. 넓은 천연 잔디마당과 대형 실외 수영장과 온수 수영장, 다양한 놀이시설, 라벤더 가든, 야채 체험장, 숲속 산책로를 갖추고 있다. 넓은 잔디 광장을 따라 설치된 민트 글램핑 사이트는 가족단위로 이용하기 좋고, 라벤더 가든을 조망할 수 있는 라벤더 글램핑 사이트는 커플들에게 인기가 많다. 개별 비비큐가 가능하며, 글램핑 내부는 개별 화장실은 물론, 냉난방 설비, 호텔식 침구까지 사계절 쾌적하다.",
        isGlamp: true,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "포천시",
        addr1: "경기 포천시 이동면 금강로 5846",
        addr2: "이동면 금강로 5846",
        mapX: 127.3749216,
        mapY: 38.0531117,
        tel: "010-5267-8229",
        homepage: "www.mintcamping.com",
        price: 225000,
        animalCmgCl: false,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이", "산책로", "운동장", "수상레저", "낚시"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "온수"],
        eqpmnLendCl: ["릴선", "화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100071/thumb/thumb_720_6222bzJtfprpnsdD6xOdlUzs.jpg",
    },
    {
        id: 15,
        name: "야한 캠핑장",
        lineIntro: "와룡산 아래 들판뷰가 좋은 카페 겸 야영장",
        intro: "한적한 야경이 아름답고 품위가 있다는 의미의 야한 캠핑장은 이천에 위치한 카페, 펜션 겸 캠핑장이다. 구 청학서당 캠핑장이 리모델링한 곳으로, 이천의 와룡산 자락에 위치한 멋들어진 전통 한옥의 카페와, 황토방 펜션이 있고, 캠핑장은 강자갈 바닥으로 총 3개의 구역으로 나눠져 있다. 장박이나 동계 캠핑도 가능하다. 뒷산으로 산책로가 있고, 사이트 수가 적어 한적하지만, 간격은 다소 좁은 느낌이다. 인근에 천주교 단내 성가정 성지, 복하천 등이 가볼 만하다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "이천시",
        addr1: "경기 이천시 마장면 이섭대천로155번길 100",
        addr2: "마장면 이섭대천로155번길 100",
        mapX: 127.3913725,
        mapY: 37.2199766,
        tel: "010-9003-6702",
        homepage: "http://xn--2f5b27n2mev2b.com/",
        price: 145000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["산책로"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "온수"],
        eqpmnLendCl: ["텐트", "릴선", "화로대", "난방기구", "식기"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100077/thumb/thumb_720_4623Y6vNd49qT8SYkWhnBEYx.jpg",
    },
    {
        id: 16,
        name: "파인벨리펜션 글램핑 2호점",
        lineIntro: "포레스트힐 골프장 옆에 있는 감성 글램핑장",
        intro: "파인벨리펜션 글램핑 2호점은 포천 포레스트힐 골프장 옆에 있는 글램핑장이다. 동명의 기존 1호점이 인기가 많아, 최근 보다 큰길 쪽으로 나와서 2호점을 개장했다. 인조 잔디에 예쁘게 꾸며진 캠핑장에서 감성 캠핑을 할 수 있다. 총 15개의 글램핑 사이트가 있는데, 내부시설이 잘 갖춰져 있어 편리하지만, 그늘이 다소 부족한 점이 아쉽다. 성인 수영장, 어린이 수영장을 갖추고 있어 온 가족이 물놀이를 즐기기 좋다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: true,
        isAuto: false,
        sigunguNm: "포천시",
        addr1: "경기 포천시 화현면 봉화로 382-1",
        addr2: "화현면 봉화로 382-1",
        mapX: 127.2783471,
        mapY: 37.8831404,
        tel: "010-2774-5726",
        homepage: "http://pglamping.hosting2003.co.kr/",
        price: 40000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        caravInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: ["가을단풍명소"],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "장작판매", "운동시설"],
        eqpmnLendCl: ["화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100083/thumb/thumb_720_8773N5XkrHyMeeilHJN6Y69c.jpg",
    },
    {
        id: 17,
        name: "노마드글램핑",
        lineIntro: "대형 호텔급 수영장과 편의시설을 갖춘 럭셔리 글램핑",
        intro: "사계절 내내 이용 가능한 온수 수영장과 독채로 운영되는 객실까지 호텔 같은 편안함을 추구하는 글램핑장이다. 텐트 앞을 관통하는 수영장, 텐트마다 설치된 100인치 스크린, 에어컨, 복층구조의 글램핑 객실은 캠핑이라기보다는 호텔에 가깝다. 저녁이면 다양한 조명으로 글램핑장의 또 다른 분위기를 느낄 수 있다. 숙소와 바비큐장이 분리되어 있어, 식사 후에도 숙소는 고기 냄새 없이 쾌적하다. 글램핑장에서 차로 5분 거리에 대형마트가 있어 식재료 등 쇼핑도 쉽다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: false,
        isAuto: false,
        sigunguNm: "가평군",
        addr1: "경기 가평군 상면 원흥길 46-12",
        addr2: "상면 원흥길 46-12",
        mapX: 127.326188,
        mapY: 37.8186686,
        tel: "031-356-4927",
        homepage: "http://nomadglamping.kr/",
        price: 135000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: ["봄꽃여행", "여름물놀이", "가을단풍명소"],
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "물놀이장",
            "운동시설",
        ],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100086/thumb/thumb_720_9786dCp7UcR4L4AV1bO3JJS0.jpg",
    },
    {
        id: 18,
        name: "캠핑679",
        lineIntro: "개별 화장실과 샤워실에 개별 공간까지 넓은 캠핑장",
        intro: "가평역에서 차로 15분 거리의 조용한 감성 캠핑장이다. 사이트는 파쇄석으로 사이트별 간격은 넓은 편이지만, 사이즈와 모양이 차이가 있어 사전에 확인 후 예약하는 것이 좋다. 사이트 앞에 이용하기 편한 개별 화장실과 샤워장, 공동으로 사용하는 개수대가 마련되어 있다. 사이트 주변을 나무들이 덮고 있고, 그 너머 계곡이 흐르고 있다. 계곡은 폭이 넓고 물이 아주 깊지는 않아 물놀이하기에도 좋은 곳이다. 단, 텐트별 최대 인원은 2인 이하로 제한하고 있다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 북면 화악산로 162-21",
        addr2: "북면 화악산로 162-21",
        mapX: 127.5609183,
        mapY: 37.8966864,
        tel: "031-959-4795",
        homepage: "https://cafe.naver.com/cp679ing",
        price: 35000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: ["여름물놀이"],
        brazierCl: "개별",
        sbrsCl: ["전기", "장작판매", "온수"],
        eqpmnLendCl: ["릴선", "화로대", "난방기구"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100094/thumb/thumb_720_9322cJD3hd9hG3Me1ezx1Bp6.jpg",
    },
    {
        id: 19,
        name: "파주캠핑장",
        lineIntro: "헤이리 인근 조용한 매너 캠핑장",
        intro: "파주캠핑장은 헤아라에서 가까운데, 서울에서 1시간 거리에 위치해 접근성이 좋은 캠핑장이다. 마트와 편의점 시설도 가까이에 있어 편리하다. 반려동물 입장이 불가능하고, 캠핑카나 트레일러도 입장할 수 없다. 제한 사항들에 대해 예약 전에 확인하는 것이 좋다. 매너 타임을 철저하게 관리하는 곳이라 조용하고 쾌적한 캠핑이 가능하다. 파쇄석 바닥에 총 21개의 사이트가 있고, 아담하고 깨끗한 캠핑장이며, 도심과 떨어져서 밤에 별을 보기도 좋다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "파주시",
        addr1: "경기 파주시 탄현면 방촌로628번길 25-45",
        addr2: "탄현면 방촌로628번길 25-45",
        mapX: 126.7219501,
        mapY: 37.79774498,
        tel: "031-542-5419",
        homepage: NaN,
        price: 145000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "트렘폴린",
            "물놀이장",
            "운동시설",
        ],
        eqpmnLendCl: ["텐트", "릴선", "화로대", "난방기구", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100103/thumb/thumb_720_5922VV0c21ld4Onw39xAHOgj.jpg",
    },
    {
        id: 20,
        name: "이천 인휴 글램핑",
        lineIntro: "넓고 시원스런 언덕위 평야 전망이 좋은 호텔급 글램핑",
        intro: "이천에 위치한 럭셔리 글램핑장이다. 총 15개의 글램핑이 있는데, 간격도 여유롭고 시설도 호텔급으로 편리하게 글램핑을 즐길 수 있다. 이중 6개는 야외 프라이빗 에어 풀이 설치되어 있다. 넓은 캠핑장 내에는 세미나실, 수영장, 잔디 광장, 노래방, 탁구장, 트램펄린, 카페, 매점을 갖추고 있다. 5분 거리에 낚시를 즐길 수 있는 진가 저수지가 있다. 인근에 가볼 만한 곳으로는 이천 온천, 도자기 공방, 봄철 산수유 축제, 여름철 연꽃축제 가을 복숭아 축제 등이 있다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: true,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "이천시",
        addr1: "경기 이천시 모가면 진상미로1385번길 221-6",
        addr2: "모가면 진상미로1385번길 221-6",
        mapX: 127.4706034,
        mapY: 37.1723396,
        tel: "031-585-8740",
        homepage: "http://inhueglamping.com",
        price: 245000,
        animalCmgCl: true,
        glampInnerFclty: [
            "침대",
            "TV",
            "에어컨",
            "냉장고",
            "유무선인터넷",
            "난방기구",
            "취사도구",
            "내부화장실",
        ],
        caravInnerFclty: NaN,
        posblFcltyCl: NaN,
        themaEnvrnCl: ["봄꽃여행"],
        brazierCl: "개별",
        sbrsCl: ["전기", "무선인터넷", "온수", "운동시설"],
        eqpmnLendCl: ["화로대"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100105/thumb/thumb_720_1282Hjrh0j21k2e2psnuxTJY.jpg",
    },
    {
        id: 21,
        name: "캠프 올모",
        lineIntro: "계곡과 잔디광장이 있는 조용하고 운치있는  캠핑장",
        intro: "캠프 올모는 넓은 잔디광장이 특징적이다. 넓은 잔디 광장은 보기만 해도 시원하지만, 특별한 노하우가 없어도 예쁜 사진을 찍을 수 있는 곳이기도 하다. 캠프 올모는 예약 시 사이트가 정해지는 것이 아니라, 여러 사이트 중 선착순 혹은 추첨으로 자리 배정을 받을 수 있다. 사이트 크기도 간격도 넓은 편이고, 샤워장과 화장실은 개별로 분리되어 있다. 특히 아이들과 함께 온 가족단위 캠퍼라면 캠핑장 계곡에서 물놀이 후 독립된 샤워실에서 따뜻한 물을 편하게 이용할 수 있어 좋다. 일반 개별사이트와 달리 2개 사이트가 하나로 되어 있는 팀캠 사이트도 따로 운영한다.",
        allar: 0,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 설악면 장수로 156-50",
        addr2: "설악면 장수로 156-50",
        mapX: 127.5092206,
        mapY: 37.61790481,
        tel: "031-585-3103",
        homepage: "https://campolmo.com/",
        price: 175000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: ["여름물놀이", "가을단풍명소"],
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "물놀이장",
            "운동시설",
        ],
        eqpmnLendCl: ["릴선", "식기", "침낭"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100111/thumb/thumb_720_81319LPH5670O9ZmnC0knyMq.jpg",
    },
    {
        id: 22,
        name: "힐사이드인가평 글램핑&캠핑",
        lineIntro:
            "가평에서 춘천 넘어가는 홍적이 고개 초입에 위치한 대형 캠핑장",
        intro: "가평 시외버스터미널에서도 30분 정도 더 들어가야 하는 가평 끝자락에 위치해 있다. 관리소를 기준으로 A, B, C, D 구역으로 나눠져 있다. 아이들이 좋아하는 수영장과 트램펄린은 C 구역에 위치해 있다. 각 구역별로 이동하기 위해서는 계단을 이용해야 한다. 화장실과 개수대는 B 구역에 배치되어 있어, 아이가 있는 가족이라면 이동 거리를 고려해 사이트를 결정하는 것이 좋다. 수영장은 어른 허벅지~허리 정도의 깊이의 큰 수영장과, 영유아도 즐길 수 있는 원형 수영장이 있다. 수영장 위로 그늘막이 설치되어 있다.",
        allar: 5000,
        featureNm: NaN,
        isGlamp: false,
        isCaravan: false,
        isAuto: true,
        sigunguNm: "가평군",
        addr1: "경기 가평군 북면 화악지암길 360",
        addr2: "북면 화악지암길 360",
        mapX: 127.5812911,
        mapY: 37.95405797,
        tel: "031-633-0700",
        homepage: "https://blog.naver.com/dwdw7141",
        price: 215000,
        animalCmgCl: true,
        glampInnerFclty: NaN,
        caravInnerFclty: NaN,
        posblFcltyCl: ["계곡 물놀이"],
        themaEnvrnCl: NaN,
        brazierCl: "개별",
        sbrsCl: [
            "전기",
            "무선인터넷",
            "장작판매",
            "온수",
            "트렘폴린",
            "물놀이장",
            "놀이터",
            "운동시설",
        ],
        eqpmnLendCl: ["릴선", "화로대", "난방기구"],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100113/thumb/thumb_720_37692H2YmqDJbK1OZnoAfiOV.jpg",
    },
];

export default CampSite;
