const CampSite = [
    {
        id: 100002,
        name: "힐링피아 카라반 글램핑 풀 캠핑장",
        lineIntro: "별보기 좋은 카라반 캠핑장",
        intro: "힐링피아 카라반 글램핑 풀 캠핑장은 어비계곡 사기막천과 유명산 벽계천이 합류하는 두물머리에 위치하고 있다. 카라반 데크의 크기는 휴식공간용과 바베큐공간을 분리 할 정도의 넓은 공간이고 각 카라반에 개별 수영장이 있다. 놀이시설로는 개별수영장 별도의 야외수영장, 어린이 암벽 ,하늘자전거,탁구대 등이 있으며, 힐링하기 좋은 전망대가 있어 밤에 별보기 좋은 카라반 캠핑장이다.",
        allar: "전체면적",
        featureNm: "",
        isGlamp: true,
        isCarvan: true,
        isAuto: true,
        sigunguNm: "경기도 가평군",
        price: 10000,
        address: "경기 가평군 설악면 유명산길 61-75",
        add2: "경기 가평군 설악면 유명산길 61-75",
        mapX: 127.4947241,
        mapY: 37.5978864,
        tel: "010-3148-9970",
        url: "http://healingpia.co.kr",
        lendEquipment: "릴선,화로대",
        toiletCo: 1,
        swrmCo: 1,
        swrmCo: 1,
        wtrplCo: 1,
        brazielCl: "개별",
        sbrsCl: "전기,무선인터넷,장작판매,온수,마트.편의점",
        glampInnerFclty: "",
        caravInnerFclty: "",
        lctCl: "산,숲,강",
        themaEnvrnC: [
            {
                tag: "액티비티",
            },
            {
                tag: "봄꽃여행",
            },
            {
                tag: "여름물놀이",
            },
            { tag: "가을단풍명소" },
            { tag: "겨울눈꽃명소" },
            { tag: "걷기길" },
        ],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100002/thumb/thumb_720_20339geHYKzGA9OjsoC0nFwX.jpg",
    },
    {
        id: 100011,
        name: "웨이브파크 카라반",
        lineIntro: "인공 서핑장 웨이브 파크에서 운영하는 카라반 숙소",
        intro: "일상의 무게를 잠시 내려놓고 힐링할 수 있는 공간이 필요하다면 지금 바로 방문해주세요. 저희 카라반은 국내 최고 업체인 STAUS사에서 최고급 시설로 제작하였고 개별 샤워실 및 화장실, TV, 냉장고, 인덕션, 전자레인지 등의 각종 편의 시설이 구비되어 있습니다. 카라반 테라스에서는 프라이빗한 바베큐를 사시사철 즐길 수 있으며 혼자 와도 좋고 가족, 연인, 친구와 함께 오면 더욱 좋은 공간입니다. 바로 옆에 웨이브 파크가 위치하고 있어 즐길거리와 먹거리도 다양합니다. 거북섬의 정취와 호수가 어우러져 마치 휴양지에 온듯한 착각을 주며 평화로운 분위기의 산책로에서 맛보는 일몰도 기가 막힙니다. 아름다운 서해의 석양을 바라보며 잊지못할 추억을 만드세요.",
        allar: "전체면적",
        featureNm: "",
        isGlamp: false,
        isCarvan: true,
        isAuto: false,
        sigunguNm: "경기도 시흥시",
        price: 10000,
        address: "경기 시흥시 거북섬둘레길 42 (정왕동)",
        add2: "경기 시흥시 거북섬둘레길 42 (정왕동)",
        mapX: 126.6806875,
        mapY: 37.3241008,
        tel: "031-420-9750",
        url: "https://wavepark.co.kr/wave/caravanInfo",
        lendEquipment: "릴선,화로대",
        toiletCo: 1,
        swrmCo: 1,
        swrmCo: 1,
        wtrplCo: 1,
        brazielCl: "개별",
        sbrsCl: "전기,무선인터넷,장작판매,온수,물놀이장,마트.편의점",
        glampInnerFclty: "",
        caravInnerFclty: "",
        lctCl: "해변",
        themaEnvrnC: [
            {
                tag: "일몰명소",
            },
            {
                tag: "수상레저",
            },
            {
                tag: "여름물놀이",
            },
            { tag: "걷기길" },
        ],
        firstImageUrl:
            "https://gocamping.or.kr/upload/camp/100011/thumb/thumb_720_5075dWVFnpgjhhh7pyVKfOaP.jpg",
    },
];

export default CampSite;
